const ALLOWED_ELEMENTS = new Set([
  'a',
  'circle',
  'defs',
  'g',
  'image',
  'line',
  'marker',
  'path',
  'rect',
  'text',
  'title',
  'tspan',
])

const ALLOWED_ATTRIBUTES = new Set([
  'aria-label',
  'class',
  'clip-path',
  'clip-rule',
  'dominant-baseline',
  'dx',
  'dy',
  'fill',
  'fill-rule',
  'focusable',
  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'height',
  'href',
  'marker-end',
  'marker-height',
  'marker-width',
  'opacity',
  'orient',
  'preserveAspectRatio',
  'refX',
  'refY',
  'role',
  'rx',
  'ry',
  'stroke',
  'stroke-dasharray',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-width',
  'svg',
  'target',
  'text-anchor',
  'text-decoration',
  'transform',
  'viewBox',
  'width',
  'x',
  'y',
  'xml:space',
  'xlink:href',
])

function isSafeUrl(value: string, allowData: boolean): boolean {
  try {
    const url = new URL(value, window.location.href)
    if (['http:', 'https:', 'mailto:', 'tel:'].includes(url.protocol)) return true
    return allowData && url.protocol === 'data:'
  } catch {
    return false
  }
}

/**
 * Sanitizes SVG generated by the trusted mindmap renderer before v-html inserts it.
 * User text is escaped by the core SVG builder; this second boundary removes
 * unexpected elements, event attributes and unsafe link/image protocols.
 */
export function sanitizeGeneratedSvg(markup: string): string {
  if (!markup) return ''

  const document = new DOMParser().parseFromString(
    `<svg xmlns="http://www.w3.org/2000/svg">${markup}</svg>`,
    'image/svg+xml',
  )
  if (document.querySelector('parsererror')) return ''

  const root = document.documentElement
  const elements = [root, ...Array.from(root.querySelectorAll('*'))]
  for (const element of elements) {
    if (!ALLOWED_ELEMENTS.has(element.localName)) {
      element.remove()
      continue
    }

    for (const attribute of Array.from(element.attributes)) {
      const name = attribute.name
      const lowerName = name.toLowerCase()
      if (lowerName.startsWith('on') || !ALLOWED_ATTRIBUTES.has(name)) {
        element.removeAttribute(name)
        continue
      }

      if (name === 'href' || name === 'xlink:href') {
        const isImage = element.localName === 'image'
        if (!isSafeUrl(attribute.value, isImage)) {
          element.removeAttribute(name)
        }
      }
    }
  }

  const serializer = new XMLSerializer()
  return Array.from(root.childNodes)
    .map((node) => serializer.serializeToString(node))
    .join('')
}
